TAApplication/Controllers/AdminController.cs
/**
 * Author:      Trevor Koenig
 * Partner:     Ben Kempers
 * Date:        12/6/2022
 * Course:      CS 4540, University of Utah, School of Computing
 * Copyright:   CS 4540 and [Ben Kempers and Trevor Koenig] - This work may not be copied for use in Academic Coursework.
 *
 * I, Trevor Koenig and Ben Kempers, certify that I wrote this code from scratch and did 
 * not copy it in part or whole from another source.  Any references used 
 * in the completion of the assignment are cited in my README file and in
 * the appropriate method header.
 *
 * File Contents
 *
 *    Contains all logic for the Admin page in the website. Allows for an Admin user to change any user's role.
 *    PS9 - added in the controller endpoints for EnrollmentTrends view as well as the get enrollment data information
 *    
 */

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Diagnostics;
using TAApplication.Models;
using System;
using Microsoft.AspNetCore.Identity;
using TAApplication.Areas.Data;
using Microsoft.EntityFrameworkCore;
using TAApplication.Data;
using TAApplication.Data.Migrations;

namespace TAApplication.Controllers
{
    public class AdminController : Controller
    {
        private readonly TAContext _context;
        private readonly ILogger<HomeController> _logger;
        private readonly UserManager<TAUser> _um;
        private readonly RoleManager<IdentityRole> _rm;

        public AdminController(TAContext context, ILogger<HomeController> logger, UserManager<TAUser> um, RoleManager<IdentityRole> rm)
        {
            _context = context;
            _logger = logger;
            _um = um;
            _rm = rm;
        }

        // GET: Admin Roles
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Admin()
        {
            if (_um == null || _rm == null)
            {
                return NotFound();
            }

            var students = _um.Users;
            var roles = _rm.Roles;

            if (students == null || roles == null)
            {
                return NotFound();
            }

            return View(_um);
        }


        /**
         * 
         * This method was written to update the database from the admin page so that the view is accurate
         * This method is called from Admin.cshtml AJAX script
         * 
         */
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public async Task<string> RoleRequest(string role, string id)
        {
            Console.WriteLine(id);
            TAUser user = await _um.FindByIdAsync(id);

            // used this webpage to assist in learning how to manage roles for users:
            // https://www.yogihosting.com/aspnet-core-identity-roles/
            switch (role) {
                case "No_Administrator":
                    await _um.RemoveFromRoleAsync(user, "Administrator");
                    break;
                case "Administrator":
                    await _um.AddToRoleAsync(user, "Administrator");
                    break;
                case "No_Professor":
                    await _um.RemoveFromRoleAsync(user, "Professor");
                    break;
                case "Professor":
                    await _um.AddToRoleAsync(user, "Professor");
                    break;
                case "No_Applicant":
                    await _um.RemoveFromRoleAsync(user, "Applicant");
                    break;
                case "Applicant":
                    await _um.AddToRoleAsync(user, "Applicant");
                    break;
            }

            return $"User: " + user.Name + " had role: " + role + " updated.";
        }


        /*
         * 
         * Return a view with controllers to query the database for custom data ranges for enrollment data
         * 
         */
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> EnrollmentTrends()
        {
            return View();
        }

        // GET:Enrollment data based on specified parameters
        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public async Task<string> GetEnrollmentData(string startDate, string endDate, string courseDeptNum)
        {
            System.Diagnostics.Debug.WriteLine(courseDeptNum.Split(' ')[1]);
            var courseNumber = int.Parse(courseDeptNum.Split(' ')[1]);

            Course? course = null;
            var allCourses = await _context.Course.ToArrayAsync<Course>();
            CourseEnrollment? enrollmentData = null;

            for (int i = 0; i < allCourses.Length; i++)
            {
                if (allCourses[i].courseNumber.Equals(courseNumber))
                {
                    course = allCourses[i];
                    enrollmentData = await _context.Enrollments.FindAsync(course.ID);
                }
            }

            if (enrollmentData == null)
            {
                return new string("");
            }
            else
            {
                var enrollmentDates = (string[])enrollmentData.dateList;
                System.Diagnostics.Debug.WriteLine(enrollmentDates[0]);
                int startIndex = 0;
                int endIndex = 0;
                for (int i = 0; i < enrollmentDates.Length; i++)
                {
                    
                    if (String.Equals(" " + startDate, enrollmentDates[i]))
                    {
                        System.Diagnostics.Debug.WriteLine(enrollmentDates[i] + " ");
                        startIndex = i;
                    }
                    if (String.Equals(" " + endDate, enrollmentDates[i]))
                    {
                        System.Diagnostics.Debug.WriteLine(enrollmentDates[i] + " ");
                        endIndex = i;
                    }
                }
                // if the enddate did not find a match include all dates
                if (endIndex == 0)
                {
                    endIndex = enrollmentDates.Length - 1;
                }

                var dates = String.Join(',', new List<string>(enrollmentDates).GetRange(startIndex, endIndex - startIndex + 1));
                var enrollments = String.Join(',', (new List<int>((int[])enrollmentData.enrollmentsList)).GetRange(startIndex, endIndex - startIndex + 1));

                return $"{dates}\n{enrollments}";
            }
        }
    }
}

TAApplication/Controllers/AvailabilitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TAApplication.Areas.Data;
using TAApplication.Data;
using TAApplication.Models;
using static System.Net.Mime.MediaTypeNames;

namespace TAApplication.Controllers
{
    public class AvailabilitiesController : Controller {
        private readonly TAContext _context;
        private readonly UserManager<TAUser> _um;

        public AvailabilitiesController(TAContext context, UserManager<TAUser> um) {
            _context = context;
            _um = um;
        }

        // GET: Availabilities
        [Authorize(Roles = "Applicant, Professor, Administrator")]
        public async Task<IActionResult> Availability(string? Id) {
            if (_context.Users == null)
            {
                return NotFound();
            }

            if (Id == null)
            {
                string? userId = _um.GetUserId(User);
                var currUser = await _um.FindByIdAsync(userId);
                return View(currUser);
            }

            var user = await _um.FindByIdAsync(Id);
            return View(user);


            //return View(await _context.Availability.ToListAsync());
        }

        /**
         * 
         * This method was written to update the database from the Availability page so that the view is accurate
         * This method is called from Availability.cshtml AJAX script
         * 
         */
        //Given array of slots, update DB to reflect the current users availability
        [HttpPost]
        [AllowAnonymous]
        public async Task<string> SetSchedule(string availabilitySlots, string id)
        {
            //uncomment this code to force an error to see the error message on screen
            // throw new System.Web.Http.HttpResponseException(System.Net.HttpStatusCode.BadRequest);

            Availability availability = new Availability();
            availability.WeekAvailability = availabilitySlots;

            ModelState.Remove("User");
            availability.User = await _um.GetUserAsync(User);

            availability.ID = availability.User.Id;
            if (ModelState.IsValid)
            {
                try {
                   _context.Add(availability);
                    await _context.SaveChangesAsync();
                }
                catch {
                    _context.Update(availability);
                    await _context.SaveChangesAsync();
                }
            }
            else
            {
                throw new System.Web.Http.HttpResponseException(System.Net.HttpStatusCode.BadRequest);
            }

            return $"User had availabilities updated to: " + availabilitySlots;
        }

        //Return an array of slots representing the current users availability
        [HttpGet]
        [AllowAnonymous]
        public async Task<string> GetSchedule(string id) {
            var availabilitySlots = await _context.Availability.FindAsync(id);

            if(availabilitySlots == null)
            {
                return new string('0', 240);
            }
            else
            {
                return $"{availabilitySlots.WeekAvailability}";
            }
        }

    /*        // GET: Availabilities/Details/5
            public async Task<IActionResult> Details(int? id)
            {
                if (id == null || _context.Availability == null)
                {
                    return NotFound();
                }

                var availability = await _context.Availability
                    .FirstOrDefaultAsync(m => m.ID == id);
                if (availability == null)
                {
                    return NotFound();
                }

                return View(availability);
            }

            // GET: Availabilities/Create
            public IActionResult Create()
            {
                return View();
            }

            // POST: Availabilities/Create
            // To protect from overposting attacks, enable the specific properties you want to bind to.
            // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
            [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Create([Bind("ID,mondayAvailability,tuesdayAvailability,wednesdayAvailability,thursdayAvailability,fridayAvailability")] Availability availability)
            {
                if (ModelState.IsValid)
                {
                    _context.Add(availability);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                return View(availability);
            }*/
}

}

TAApplication/Controllers/CoursesController.cs
/**
 * Author:      Trevor Koenig
 * Partner:     Ben Kempers
 * Date:        10/23/2022
 * Course:      CS 4540, University of Utah, School of Computing
 * Copyright:   CS 4540 and [Ben Kempers and Trevor Koenig] - This work may not be copied for use in Academic Coursework.
 *
 * I, Trevor Koenig and Ben Kempers, certify that I wrote this code from scratch and did 
 * not copy it in part or whole from another source.  Any references used 
 * in the completion of the assignment are cited in my README file and in
 * the appropriate method header.
 *
 * File Contents
 *
 *   This Controller is responsible for managing what data is displayed to whom for each course
 *   If a malformed request is made this controller should detect that
 *    
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using TAApplication.Data;
using TAApplication.Models;
using static System.Net.Mime.MediaTypeNames;
using Microsoft.AspNetCore.Identity;
using TAApplication.Areas.Data;

namespace TAApplication.Controllers
{
    public class CoursesController : Controller
    {
        private readonly TAContext _context;
        private readonly UserManager<TAUser> _um;

        public CoursesController(TAContext context, UserManager<TAUser> um)
        {
            _context = context;
            _um = um;
        }

        // GET: Courses
        [Authorize(Roles = "Administrator, Professor")]
        public async Task<IActionResult> List()
        {
              return View(await _context.Course.ToListAsync());
        }

        // GET: Courses/Details/5
        [Authorize(Roles = "Professor, Administrator")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Course == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .FirstOrDefaultAsync(m => m.ID == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Courses/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create([Bind("ID,semesterOffered,yearOffered,courseTitle,courseDepartment,courseNumber,courseSection,courseDescription,profUNID,profName,daysOffered,timeOffered,courseLocation,creditHours,courseEnrollment,Note")] Course course)
        {
            ModelState.Remove("User");
            course.User = await _um.GetUserAsync(User);
            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(List));
            }
            return View(course);
        }

        // GET: Courses/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Course == null)
            {
                return NotFound();
            }

            var course = await _context.Course.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int id, [Bind("ID,semesterOffered,yearOffered,courseTitle,courseDepartment,courseNumber,courseSection,courseDescription,profUNID,profName,daysOffered,timeOffered,courseLocation,creditHours,courseEnrollment,Note")] Course course)
        {
            if (id != course.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(List));
            }
            return View(course);
        }

        // GET: Courses/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Course == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .FirstOrDefaultAsync(m => m.ID == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Course == null)
            {
                return Problem("Entity set 'TAContext.Course'  is null.");
            }
            var course = await _context.Course.FindAsync(id);
            if (course != null)
            {
                _context.Course.Remove(course);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(List));
        }

        private bool CourseExists(int id)
        {
          return _context.Course.Any(e => e.ID == id);
        }
    }
}

TAApplication/Views/Shared/_Layout.cshtml
<!--
  Author:    Ben Kempers & Trevor Koenig
  Date:      9/8/2022
  Course:    CS 4540, University of Utah, School of Computing
  Copyright: CS 4540 and [Ben Kempers and Trevor Koenig] - This work may not be copied for use in Academic Coursework.

  I, Ben Kempers and Trevor Koenig, certify that I wrote this code from scratch and did not copy it in part or whole from
  another source.  Any references used in the completion of the assignment are cited in my README file.

  File Contents

     Layout page that holds the Navbar and other elements that are used in every other .cshtml page.
     This page is slightly dynamic in that based on who you are signed in as you will see a different navbar linking to different pages
-->
@using TAApplication.Areas.Data
@using Microsoft.AspNetCore.Identity
@inject SignInManager<TAUser> SignInManager
@inject UserManager<TAUser> UserManager
@inject TAApplication.Data.TAContext _context

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TAApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TAApplication.styles.css" asp-append-version="true" />

    <!-- Datatable CDN Link -->
    @section Styles{
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">
    }
    </head>
    <body>
        <header>
            <nav class="navbar navbar-expand-lg bg-light">
                <div class="container-fluid">
                    <input type="image" id="nav_title" src="/Images/Favicon.ico" onclick="location.href=" Index";">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNavDropdown">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            var student = await UserManager.FindByEmailAsync(User.Identity?.Name);
                            var studentRolesList = await UserManager.GetRolesAsync(student);
                            foreach (String role in studentRolesList)
                            {
                                if (role.Equals("Administrator"))
                                {
                                    <li>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Applications" asp-action="List">Application List</a>
                                    </li>
                                    <li>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Admin">Admin Page</a>
                                    </li>
                                    <li>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Applications" asp-action="Index">Index Page</a>
                                    </li>
                                    <li>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="List">Course Page</a>
                                    </li>
                                    break;
                                }
                                else if (role.Equals("Professor"))
                                {
                                    <li>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Applications" asp-action="List">Application List</a>
                                    </li>
                                    break;
                                }
                                else if (role.Equals("Applicant"))
                                {
                                    <li>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Applications" asp-action="Details">Application Details</a>
                                    </li>
                                    <li>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Applications" asp-action="Create">Application Create</a>
                                    </li>
                                    break;
                                }
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        }
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" asp-area="" asp-controller="" asp-action="#" role="button" id="navbarDropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                TA
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                @if (SignInManager.IsSignedIn(User))
                                {
                                    var student = await UserManager.FindByEmailAsync(User.Identity?.Name);
                                    <li>@student.Name</li>
                                }
                                else
                                {
                                    <li>User Name</li>
                                }
                                <li>
                                    <div class="dropdown-divider">PS9</div>PS9
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="EnrollmentTrends">Enrollment Trends</a>
                                </li>
                                <li>
                                    <div class="dropdown-divider">PS8</div>PS8
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Availabilities" asp-action="Availability">Availabilities Page</a>
                                </li>
                                <li>
                                    <div class="dropdown-divider">PS6</div>PS6
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="List">Course Page</a>
                                </li>
                                @{
                                    //Course u0000001 = await UserManager.FindByEmailAsync("u0000001@utah.edu");
                                    var course = _context.Course.FirstOrDefault(o => o.courseNumber == 1400);
                                    int? firstCourse = null;
                                    if (course != null) {
                                        firstCourse = course.ID;
                                    }
                                }
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Details" asp-route-id="@firstCourse">Details Page</a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Edit" asp-route-id="@firstCourse">Update Page</a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Create">Create Page</a>
                                </li>
                                <li>
                                    <div class="dropdown-divider">PS5</div>PS5
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Applications" asp-action="Index">Index Page</a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Applications" asp-action="List">Applications List</a>
                                </li>

                                @{
                                    TAUser u0000001 = await UserManager.FindByEmailAsync("u0000001@utah.edu");
                                    var app = _context.Application.FirstOrDefault(o => o.User == u0000001);
                                    int? Id = null;
                                    if (app != null)
                                    {
                                        Id = app.ID;
                                    }
                                }
                                <li>
                                    <a class="nav-link text-dark" asp-controller="Applications" asp-action="Details" asp-route-id="@Id">Applications Details</a>
                                </li>

                                <li>
                                    <div class="dropdown-divider">Admin</div>Admin
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Admin">Admin Page</a>
                                </li>

                                <li>
                                    <div class="dropdown-divider">OLD</div>OLD
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="OLD" asp-action="ApplicationList">Application List OLD</a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="OLD" asp-action="ApplicationCreate">Application Create OLD</a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="OLD" asp-action="ApplicationDetails">Application Details OLD</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TAApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("Styles", required: false)
</body>
</html>